### ISSUE TITLE
abbility to play a random clip once 

### ISSUE THREAD

**Issue by BlackBullNetwork** [teklynk/twitch_clips_player#2]
i would love to use this but i am looking for a clip player that grabs a random clip and plays it once and then stops untill you do the command again is that possible for this system cause it looks amazing

**Comment by teklynk** [comment]
Maybe the Shoutout Clips Player will work for you? It plays a random clip when a command like: "!so teklynk" is used in chat. You can find that here: https://github.com/teklynk/twitch_shoutout

Or do you want it to play one of your own clips when a chat command like: "!playclip" is used?

The clips player can already use a custom command that you can set. .
Type "!mycommand" to start the clips player.
Type "!mycommand stop" to stop the clips player.

You can try it here: https://twitch-clips-player.pages.dev
