### ISSUE TITLE
This tool, alongside other Twitch Clip Player tools, would fetch the clip, play video/audio for a couple seconds, then freeze

### ISSUE THREAD

**Issue by AyomideCode** [teklynk/twitch_clips_player#3]
It would fetch the clip, play video/audio for a couple seconds, then freeze. But it would keep fetching the next clip, then freeze again. 

I've tested this for this tool, https://github.com/ShaderWave/RandomClipPlayer, https://twitch.guru/clipsworks, and https://streamgood.gg/clips. All would have the same problem occur on both OBS and Chrome, and I tested other channels big and small too.

When I told the fellows at the TwitchDev Discord server proposing it was an API problem, one of them stated:
"There's no supported 3rd party players for Clips or VoDs
Twitch Embeds https://dev.twitch.tv/docs/embed/ are the supported way to display clips"

**Comment by teklynk** [comment]
Be sure to Enable OBS browser source hardware acceleration in Settings -> Advanced in OBS.

If viewing the clips player in a browser outside of OBS, the window need to be active and the user needs to interact with the window. This was something added by chrome to prevent videos from auto playing in tabs that are not active (such as with video ads). 

Try adding this test video as a browser source in OBS https://twitch-shoutout.pages.dev/videotest The test video does not use Twitch's api. It is just a simple html5 video player.

**Comment by AyomideCode** [comment]
Thanks for the quick response. I tested with the video and it didn't work; so it was an issue on my end.
The first thing you suggested worked for me.
