### ISSUE TITLE
Filter clips by game

### ISSUE THREAD

**Issue by Stackmandu** [teklynk/twitch_clips_player#5]
Would love the ability to set a parameter to only feature clips from 'x' game

Thanks for making a great tool!

**Comment by teklynk** [comment]
Great idea. I will look into seeing what it will take to add that feature. I'll let you know when it is ready to test.

**Comment by teklynk** [comment]
@Stackmandu I have added the feature to filter clips by game title/category. Currently it only supports one title. The game title must be exactly as is it on Twitch. You can add &gameTitle=Retro to your URL or re-visit the Clips generator page and use the new Filter by Game Title field. Let me know if you run into any issues.

**Comment by Stackmandu** [comment]
Wow, what a speedy implementation!
Have just updated it for myself and it works great!
Thanks heaps!

(have recently gone from streaming a variety of games, to only Valorant. This means I can keep my clips in context to my current content, super appreciative of your work :) )
