### ISSUE TITLE
Player Lags and Freezes

### ISSUE THREAD

**Issue by xSlizzy** [teklynk/twitch_clips_player#7]
After inserting the clips player into my OBS I noticed the clips often lag and often freezes and jumps around. Any suggestions on a fix? I'm running a Gigabyte 4080 so my card shouldn't be the issue.

**Comment by teklynk** [comment]
Hello.
Make sure that hardware acceleration is enabled. Enable browser source optimization in advanced settings in OBS.

**Comment by xSlizzy** [comment]
Hello, thank you for your response. Unfortunately it already is enabled. I have it pulling up to 100 clips, could that factor into the lag?

**Comment by teklynk** [comment]
Hmm. I am really not sure. Ussually hardware acceleration fixes the lag issues. Can you try adding this as a browser source to see if it also lags? https://twitch-shoutout.pages.dev/videotest

You can also try using the shoutout player from Twitch Guru to see if that one also lags. https://www.twitch.guru/tools/soclip.html

**Comment by xSlizzy** [comment]
No lag with your videotest link, but the Twitch Guru shoutout is lagging.

I appreciate your help thus far. If you have any other suggestions, I am all ears.

**Comment by xSlizzy** [comment]
To add a little more context, the first clip always plays fine, then as it transitions to the 2nd clip it begins to lag and slowly gets progressively worse as more clips play to the point where it looks like the clip is playing at 0.2x speed.

**Comment by xSlizzy** [comment]
Well, I disabled hardware acceleration and that seems to have helped a lot. Still a bit buggy in transitions, but the clips appear to be playing much better overall.

Sorry for all the messages.

**Comment by teklynk** [comment]
Thank you for testing these things out. The only time I have seen this issue was with something related to hardware acceleration. I have created another video test url. This one is using a clip from Twitch. https://twitch-clips-player.pages.dev/videotest 

I am trying to figure out if this is something in OBS or something with Twitch. 
What version of OBS are you using?

**Comment by xSlizzy** [comment]
No problems with your new test link. Works fine with acceleration on and off.

I am on OBS version 29.1.3 (64 bit)

**Comment by teklynk** [comment]
I have been testing in OBS 30.0.1 but I recall that it also worked fine in versions as far back as 27.0.0. 

A few things you can try is:
On the browser source properties for the clips player
set FPS to 60
check/enable: Shutdown source when not visible, Refresh browser when scene becomes active, control audio via OBS.
